// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'FeedPost': typeof import("../components/feedPost.vue")['default'],
    'MainSection': typeof import("../components/mainSection.vue")['default'],
    'UISpinner': typeof import("../components/UI/spinner.vue")['default'],
    'LogoTwitter': typeof import("../components/logo/twitter.vue")['default'],
    'SidebarLeft': typeof import("../components/sidebar/left/index.vue")['default'],
    'SidebarLeftTab': typeof import("../components/sidebar/left/tab.vue")['default'],
    'SidebarRight': typeof import("../components/sidebar/right/index.vue")['default'],
    'SidebarRightPreviewCard': typeof import("../components/sidebar/right/previewCard/index.vue")['default'],
    'SidebarRightPreviewCardItem': typeof import("../components/sidebar/right/previewCard/item.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyFeedPost': typeof import("../components/feedPost.vue")['default'],
    'LazyMainSection': typeof import("../components/mainSection.vue")['default'],
    'LazyUISpinner': typeof import("../components/UI/spinner.vue")['default'],
    'LazyLogoTwitter': typeof import("../components/logo/twitter.vue")['default'],
    'LazySidebarLeft': typeof import("../components/sidebar/left/index.vue")['default'],
    'LazySidebarLeftTab': typeof import("../components/sidebar/left/tab.vue")['default'],
    'LazySidebarRight': typeof import("../components/sidebar/right/index.vue")['default'],
    'LazySidebarRightPreviewCard': typeof import("../components/sidebar/right/previewCard/index.vue")['default'],
    'LazySidebarRightPreviewCardItem': typeof import("../components/sidebar/right/previewCard/item.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const FeedPost: typeof import("../components/feedPost.vue")['default']
export const MainSection: typeof import("../components/mainSection.vue")['default']
export const UISpinner: typeof import("../components/UI/spinner.vue")['default']
export const LogoTwitter: typeof import("../components/logo/twitter.vue")['default']
export const SidebarLeft: typeof import("../components/sidebar/left/index.vue")['default']
export const SidebarLeftTab: typeof import("../components/sidebar/left/tab.vue")['default']
export const SidebarRight: typeof import("../components/sidebar/right/index.vue")['default']
export const SidebarRightPreviewCard: typeof import("../components/sidebar/right/previewCard/index.vue")['default']
export const SidebarRightPreviewCardItem: typeof import("../components/sidebar/right/previewCard/item.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyFeedPost: typeof import("../components/feedPost.vue")['default']
export const LazyMainSection: typeof import("../components/mainSection.vue")['default']
export const LazyUISpinner: typeof import("../components/UI/spinner.vue")['default']
export const LazyLogoTwitter: typeof import("../components/logo/twitter.vue")['default']
export const LazySidebarLeft: typeof import("../components/sidebar/left/index.vue")['default']
export const LazySidebarLeftTab: typeof import("../components/sidebar/left/tab.vue")['default']
export const LazySidebarRight: typeof import("../components/sidebar/right/index.vue")['default']
export const LazySidebarRightPreviewCard: typeof import("../components/sidebar/right/previewCard/index.vue")['default']
export const LazySidebarRightPreviewCardItem: typeof import("../components/sidebar/right/previewCard/item.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
